
using IPSTemplate.Dal.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualBasic;
using NetTopologySuite.Algorithm;
using RTools_NTS.Util;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics.Metrics;
using System.Diagnostics;
using System;
using System.Net.NetworkInformation;
using static System.Net.Mime.MediaTypeNames;
using static System.Reflection.Metadata.BlobBuilder;
using System.Numerics;
using System.Runtime.ConstrainedExecution;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics.X86;

namespace Core.DALEF.ContextFactory.Seeds
{
    public class TEBookSeed : List<TEBook>
    {
        public TEBookSeed()
        {
            Add(new() { Id = new Guid("9a27d8d9-b415-489b-bd35-dc1730200dbf"), Name = "Free! Love Your Work, Love Your Life", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Life and work are intrinsically linked. They are not separate; they are one. If we want to live an extraordinary life, we have to make our work equally extraordinary. When your work resonates with purpose, you jump out of bed every morning, excited by the possibilities the day holds for you. Everything else in your life seems to have a glow about it, and you exude much more personal shine. My aim in writing this book is to help you feel like that every day. To help you make your work work for you. To feel truly free. Reading Free! will remind you that you are fantastic and have the ability to do amazing things; show you that work is your slave, not the other way round; help you make work your ticket to an extraordinary future; and put you in the driving seat and show you a route to freedom.", BookIndex = 100 });
            Add(new() { Id = new Guid("febca16c-9fce-4d75-b7d1-177bfa143db1"), Name = "Clean Code: A Handbook of Agile Software Craftsmanship", GenreID = new Guid("E74EC0D0-4F62-424A-A876-1ED6815E9DE5"), Active = true, Description = "Even bad code can function. But if code isn&rsquo;t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn&rsquo;t have to be that way. Noted software expert Robert C. Martin presents a revolutionary paradigm with  Clean Code: A Handbook of Agile Software Craftsmanship . Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code &ldquo;on the fly&rdquo; into a book that will instill within you the values of a software craftsman and make you a better programmer&mdash;but only if you work at it. What kind of work will you be doing? You&rsquo;ll be reading code&mdash;lots of code. And you will be challenged to think about what&rsquo;s right about that code, and what&rsquo;s wrong with it. More importantly, you will be challenged to reassess your professional values and your commitment to your craft.   Clean Code  is divided into three parts. The first describes the principles, patterns, and practices of writing clean code. The second part consists of several case studies of increasing complexity. Each case study is an exercise in cleaning up code&mdash;of transforming a code base that has some problems into one that is sound and efficient. The third part is the payoff: a single chapter containing a list of heuristics and &ldquo;smells&rdquo; gathered while creating the case studies. The result is a knowledge base that describes the way we think when we write, read, and clean code. Readers will come away from this book understanding  How to tell the difference between good and bad code How to write good code and how to transform bad code into good code How to create good names, good functions, good objects, and good classes How to format code for maximum readability How to implement complete error handling without obscuring code logic How to unit test and practice test-driven development This book is a must for any developer, software engineer, project manager, team lead, or systems analyst with an interest in producing better code.", BookIndex = 200 });
            Add(new() { Id = new Guid("3678e8e4-7716-42ae-98a2-277adab4bccc"), Name = "Pojej živo žabo", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "21 cudovitih nacinov, da prenehate prelagati na jutri, kar lahko storite danes, in v manj casa opravite vec", BookIndex = 300 });
            Add(new() { Id = new Guid("c5fa5dfb-44a3-4ddb-90c6-2f9617221bdd"), Name = "360° vodja", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Razvijanje vašega vpliva od kjerkoli znotraj posamezne organizacije", BookIndex = 400 });
            Add(new() { Id = new Guid("8feb709d-b1e1-40e6-9b47-c4b8d9d23412"), Name = "Moc neuspeha", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "27 nacinov, kako spremeniti neuspeh v uspeh \r\n\r\nRecepti za ustvarjalno, uspešno in mirno življenje", BookIndex = 500 });
            Add(new() { Id = new Guid("e4f1011a-d6b3-4d12-908d-9ba618a3f3ab"), Name = "Ucinkovito reševanje konfliktov", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Preprosta in ucinkovita metoda v 4. korakih, s katero se boste v vsakdanjem življenju lažje sporazumevali in dogovarjali", BookIndex = 600 });
            Add(new() { Id = new Guid("d8c6cf0d-16b7-4197-bd3b-70faf2341b6e"), Name = "Skrivnost ustvarjalnega tima", GenreID = new Guid("9147B105-9B2B-4D11-8F19-64D2A588CD44"), Active = true, Description = "", BookIndex = 700 });
            Add(new() { Id = new Guid("a4c539aa-ad89-437c-8767-ff5bebaf83a7"), Name = "Pozitivna naravnanost in ustvarjalnost pri delu", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Postanite uspešnejši in ustvarite življenje, ki si ga želite", BookIndex = 800 });
            Add(new() { Id = new Guid("a2d96655-ab60-46cb-af2b-d31144f6b91d"), Name = "Pozitivni naboj", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Šest pozitivnih povezav z uspehom", BookIndex = 900 });
            Add(new() { Id = new Guid("081bc263-1bfb-4c65-aeb5-5725bc134903"), Name = "Mravlja in slon", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Postanite sam svoj vodja\r\n\r\nKako v 5 korakih povecati ucinkovitost vašega dela", BookIndex = 1000 });
            Add(new() { Id = new Guid("aa849042-ecd7-476d-b296-610c83240ad0"), Name = "Psiho-kibernetika", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Enostavne, znanstven, revolucionaren program za zdravje in uspeh slovitega ameriškega zdravnika", BookIndex = 1100 });
            Add(new() { Id = new Guid("868852d4-8bb6-473e-963f-3d2588e3c068"), Name = "Recite DA svojemu potencialu", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Ce ste kot vecina ljudi, uporabljate samo okoli deset odstotkov svojega potenciala, ostalih devetdeset odstotkov pa spada v kategorijo \"lahko bi\"", BookIndex = 1200 });
            Add(new() { Id = new Guid("e3553e15-459c-4585-9790-00421af356e1"), Name = "Ce zmorem jaz, zmoreš tudi ti!", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Tudi vi lahko v življenju \"rastete\" - ne pa ga samo preživljate - premagate nemogoce okolišcine in dosežete sreco in uspeh! \r\nDramaticna življenska zgodba Mammie McCullough nazorno dokazuje, da pozitivno mišljenje ni samo nadve ucinkovito, marvec nam prinaša tudi globoko zadošcenje.", BookIndex = 1300 });
            Add(new() { Id = new Guid("7a042797-0838-4b93-8779-51e4364d3cc4"), Name = "Hiti pocasi", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Kako obvladovati cas in ponovno vzpostaviti ravnotežje v življenju", BookIndex = 1400 });
            Add(new() { Id = new Guid("c6686738-c897-4e32-9c3f-7e0ac9d25f64"), Name = "Dieta brez diete", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Znanstveniki so odkrili skrivnost zdravega in trajnega hujšanja, ki sploh nima opravka z dieto!\r\n\r\nLjudje imajo cezmerno telesno težo, ker so ujetniki škodljivih navad. Priricnik Dieta brez diete vam pokaže, kako se lahko znebite skritih navad, da boste shujšali brez truda in obcutka lakote.", BookIndex = 1500 });
            Add(new() { Id = new Guid("f11b616b-51c9-47bd-9d82-794b056781f4"), Name = "Postanite voditelj", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "", BookIndex = 1600 });
            Add(new() { Id = new Guid("1bdbc2a2-488a-412e-b047-82de20caab26"), Name = "Ucinkoviti vodja", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Pricujoca knjiga je namenjena vodstvenim delavcem, svetovalcem in podjetnikom, ki želijo postati ucinkoviti vodje in vsem, ki razmišljajo o zamenjavi službe, ki se s težavo soocajo s spremembami in išcejo nove možnosti za razvoj in napredek tako na poslovnem kot osebnem podrocju", BookIndex = 1700 });
            Add(new() { Id = new Guid("1c4445be-66eb-4f6c-9c29-511247ddeacf"), Name = "Digitalna transformacija in poslovne informacijske rešitve", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "", BookIndex = 1800 });
            Add(new() { Id = new Guid("85f2bbf0-ab49-4153-beb9-226af992767b"), Name = "Osnovne vešcine postavljanja vprašanj", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Najucinkovitejši pogovor je sestavljen iz 20 % odgovorov in 80 % spraševanja", BookIndex = 1900 });
            Add(new() { Id = new Guid("d14ba13b-e446-422a-a6cb-cbe0ef355d0b"), Name = "Zapomnite si vsako ime", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Nikoli vec ne boste rekli, da imate slab spomin za imena in obraze", BookIndex = 2000 });
            Add(new() { Id = new Guid("cd461206-e127-4b46-931f-f448623ea7b0"), Name = "Custvena inteligenca", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Kratek vodnik ponuda konkretne odgovore, kako:\r\n- Uporabiti štiri edinstvena podrocja custvene inteligence: samozavedanje, samoupravljanje, družbeno zavedanje in upravljanje medosebnih odnosov\r\n- Dvigniti raven custvene inteligence s tehnikami usposabljanja\r\n- Uporabiti custveno inteligenco pri delu za razvoj sposobnosti vodenja in izboljšanje ucinkovitosti timskega dela, kar nam omogoca, da postanemo boljši vodja oziroma bolj priljubljen sodelavec\r\n- Uporabiti custveno inteligenco v praksi izven delovnega okolja z najbližjimi, tako da postanemo boljši partnerji in starši\r\n- Doseci povezavo med custveno inteligenco in dobrim telesnim pocutjem\r\n- Izmeriti trenutno raven custvene inteligence s preizkusom na spletu", BookIndex = 2100 });
            Add(new() { Id = new Guid("c676c6ba-a951-426c-bd8e-503609aecbe3"), Name = "Kako spretno komunicirati z ljudmi", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Želja, da bi nas drugi prepoznali, da bi se cutili bolj pomembne in cenjene, najbolj prevladuje. In bolj pomembne ko se drugi pocutijo ob vas, bolj pozitivno se bodo odzvali na vas", BookIndex = 2200 });
            Add(new() { Id = new Guid("b6acf3f2-affc-4429-9232-5cc4e950f2da"), Name = "Kako premagati casovno revšcino", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Kaj je današnja najvecja težava?\r\nPomanjkanje casa!\r\nO tem govorijo vsi. POmanjkanje casa skrbi vse nas, a doslej ni še nihce ponudil rešitve, kako to težavo odpraviti.\r\n\r\nZakaj ljudem primanjkuje casa?\r\nKer svoj cas v službi menjajo za denar. Denar potrebujejo, zato \"prodajajo\" svoj cas. POtrebujejo vec denarja, zato prodajajo vec casa. Kmalu toliko casa namenijo služenju denarja, da imajo bore malo casa za karkoli drugega.\r\n\r\nKakšna je rešitev?\r\nSvoj cas zacnite menjati za KAPITAL, ki mu potem dopustite, naj dela za vas in vam prinaša prihodke, ki jih potrebujete za uresnicitev svojih sanj. Tako boste imeli vec casa za pomembne stvari, cas za družino in prijatelje, cas za rekreacijo in cas za užvanje življenja.\r\n\r\nBill Quain v svoji knjigi ljudem pojasni, zakaj nimajo casa. Potem pa svojim bralcem predstavi pet preprostih korakov, kako lahko delajo manj, ustvarijo vec in premagajo casovno revšcino.", BookIndex = 2300 });
            Add(new() { Id = new Guid("c05bc45d-013a-497a-83f5-1ca7418f1011"), Name = "Sanjaci nikoli ne spijo", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Ta knjiga, od katere se ne boste mogli lociti, vam bo pomagala slediti in uresnicevati vaše sanje. Pat Mesiti vam na zabaven in izzivalen nacin pokaže, kako:\r\n- napacna dojemanja zamenjate z zmagovalnimi pristopi\r\n- pridobite nove prijatelje\r\n- sami dolocite svojo usodo\r\n- presežete meje svojih sposobnosti\r\n- premagate neuspeh\r\n- odkrijete, kaj je pravi uspeh in kako preoblikuje vaš svet", BookIndex = 2400 });
            Add(new() { Id = new Guid("ff9354d2-ace1-4de9-8cf9-42d204a50923"), Name = "Notranji zmagovalec", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Življenski nacrt za timske igralce", BookIndex = 2500 });
            Add(new() { Id = new Guid("86eee0ac-d137-49ef-827d-3e44d61c5a64"), Name = "Osebnostna sestavljanka", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Skozi situacije iz resnicnega življenja in prek zabavnih osebnih anekdot vam Littauerjevi pokažeta, kako naj bi se najbolje odzvali na reakcijo prijateljev in sodelavcev. Vam ni jasno, zakaj je vaš partner užaljen? Se sprašujete, zakaj se je kolegica tako \"cudno\" oblekla? Vas zanima, koga postaviti na novo delovno mesto? Kakšne oglase napisati za razlicne tipe ljudi? Komu zaupati rutinsko delo? Kdo bo bolje opravil kreativni del naloge? Kako to, da je sodelavec nervozen, ceprav rok za izvedbo projekta potece šele cez en mesec? To je le nekaj vprašanj, na katere boste v knjigi našli številne koristne odgovore", BookIndex = 2600 });
            Add(new() { Id = new Guid("a50e2b66-93b3-4a7c-9642-52bfe9959a7e"), Name = "Cudež motivacije", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Je pot...\r\nSo cilji...\r\nSo želje...\r\n\r\nZakaj je motivacija cudež?\r\n\r\nKer z njo uspete...\r\nKer z njo premagate težave...\r\nKer z njo dosežete vaše življenjske cilje...", BookIndex = 2700 });
            Add(new() { Id = new Guid("4acd1fab-00d4-4d57-9ab8-978bb6eb07ac"), Name = "9 laži, zaradi katerih vaš posel ne uspeva, kot bi lahko... in resnica, ki ga bo osvobodila", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Chandler in Beckford razgaljata devet najpogostejših (in ponavadi usodnih) poslovnih mitov in ponujata preproste in navdihujoce rešitve za težave, ki si jih samostojni podjetniki ter lastniki majhnih podjetij povzrocajo iz dneva v dan. Presenetljive resnice, ki predstavljajo protistrup tem lažem, so Sam Beckford in vec sto njegovih strank, uspešnih samostojnih podjetnikov ter lastnikov majhnih podjetij, sami preizkusili\r\n\r\nTo sveže, živahno \"sveto pismo za poslovneže\" vam bo razkrilo, kaj in kako morate poceti, da bi vaš posel postal dobickonosen. V knjigi boste  odkrili tudi sestavino, ki v mnogih \"prakticnih\" poslovnih prirocnikih manjka - kako se iz dneva v dan motivirati, da bi te stvari dejansko lahko poceli", BookIndex = 2800 });
            Add(new() { Id = new Guid("1ad5e814-119c-4323-a613-87e99873e67f"), Name = "V odvisnosti od službe", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Namesto da išcete službo, zacnite iskati priložnosti", BookIndex = 2900 });
            Add(new() { Id = new Guid("54e2f7dc-0de3-4afa-9266-28638a0738c1"), Name = "Sprožilci", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "30 prodajnih orodij, s katerimi lahko nadzorujete misli vaše stranke, jo motivirate, vplivate nanjo in jo prepricate v nakup.", BookIndex = 3000 });
            Add(new() { Id = new Guid("5d9ccdeb-153e-4c8b-ba53-67cb2299c689"), Name = "Cena priložnosti", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Razmerje med ceno in dobickom in kaj to pomeni za vaše podjetje", BookIndex = 3100 });
            Add(new() { Id = new Guid("09c427f8-e752-4754-a3a2-7318ee63564b"), Name = "Prodajajte odgovorno", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Kako hitro in manj stresno zaslužiti vec", BookIndex = 3200 });
            Add(new() { Id = new Guid("beafa43f-5215-4f51-91e8-5d6c0aca2dad"), Name = "Zmagovalni odnos", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Pot do vašega osebnega uspeha", BookIndex = 3300 });
            Add(new() { Id = new Guid("640a6b5a-feea-4312-9d87-567fd465adf1"), Name = "Zmagovalci", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Kako posameznike povezati v uspešen tim!", BookIndex = 3400 });
            Add(new() { Id = new Guid("4fe5155b-a047-4a08-b7d9-baf24ea6a581"), Name = "Brez tveganja ni uspeha", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Uspeha ne bo, ce boste nanj cakali. Knjiga vam bo razkrila, kaj morate storiti, da bi se zgodila prave stvari.", BookIndex = 3500 });
            Add(new() { Id = new Guid("a770ffb6-a764-446b-b9ff-6cd966c92147"), Name = "Surrounded by Setbacks", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "How to handle everything (and everyone) around you when all hell breaks loose, from the international bestselling author of Surrounded by Idiots . Not everything goes the way we want it to - the world or people around us sometimes just spin out of control. Just consider the Covid pandemic for starters. Or how about that mad neighbour you have living next-door to you? Or when work seems to be going down the toilet when the competition keep outsmarting you? So how do you handle everything life throws your way when you'd really prefer to tell everyone to get stuffed?Thomas Erikson will help you turn adversity into success with the help of the behavioural model made famous in Surrounded by Idiots . Starting by reminding us that life is as it is, Erikson helps you see that it is in fact useless to try to control everything happening around you. Instead of protesting when life throws you curveballs, focus instead on how to handle them. Just as you keep the weeds away from the garden to provide space and amazing flowers, you need to find an approach to adversity that works for you and will give you the chance to turn everything into success. Surrounded by Setbacks will help you pinpoint the approach that works for you and will entertain and empower you in equal measure.", BookIndex = 3600 });
            Add(new() { Id = new Guid("96856727-b094-4e6f-941c-d15bf44d766f"), Name = "Key Management Development Models Travel", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "'A very practical, engaging guide to the essential tools which managers at all levels need to be effective themselves and to develop others. Highly recommended.' Stuart Chambers, former CEO of Pilkington plc       Key Management Development Models gives you, at a glance, instant access to a full range of the best models available for developing your management skills and helping others to work and perform at their peak.       For anyone seeking to develop their management skills it can be hard to know where to begin. Key Management Development Models explains the tools in detail - what they are and when and how to use them, with key practical tips. It's like having your very own management development coach on hand explaining all the tools that you will ever need to know. EXPERT GUIDANCE FOR YOUR MANAGEMENT CAREER", BookIndex = 3700 });
            Add(new() { Id = new Guid("9527dea2-51f6-44d9-a681-8bc846b9c557"), Name = "Skrivnost", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Kaj vedo in pocnejo odlicni vodje\r\n\r\nV knjigi boste izvedeli:\r\n- kaj morate narediti, da boste resnicno navdihnili in motivirali druge ljudi\r\n- zakaj dobre vodje skrbi prihodnost\r\n- katera tri podrocja zahtevajo stalne izboljšave\r\n- kako lahko znatno okrepite svojo vodstveno kredibilnost - ali pa jo nezavedno unicite\r\n- kateri dve komponenti sta bistveni za resnicen uspeh in vodenje - in še veliko vec.", BookIndex = 3800 });
            Add(new() { Id = new Guid("a9830403-ee09-4cc7-a8b4-84149a961297"), Name = "Skrivnosti vrhunskega prodajalca", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "O uspehu se ne govori.Martin Limbeck pa ni skromen.Na glas si upa povedati, da mu je uspelo. Še več. Pove, kako je uspelo njemu in kako lahko tudi nam.	", BookIndex =  3900 });
            Add(new() { Id = new Guid("0a4604ea-9aa8-4338-a95d-318f67d5362d"), Name = "25 need - to - know key performance indicators", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "With the critical Key Performance Indicators required to understand your employees, financials and customers, this book tells you what you need to know, fast.	", BookIndex =  4000 });
            Add(new() { Id = new Guid("8d61fbb6-c622-478e-9496-18f2f79d9bd1"), Name = "The Strategy Book, 2nd Edition ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Using the science of strategy, The Strategy Book will help you tackle the really important challenges you face both in developing strategies and putting them into action.Its aim is to give you best ideas wrapped up in a usable, enjoyable package.", BookIndex =  4100 });
            Add(new() { Id = new Guid("c13049c8-2291-45fd-9858-22d8601c6edc"), Name = "Awaken the Giant Within", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Wake up and take control of your life!From the bestselling author of Inner Strength, Unlimited Power, and MONEY Master the Game, Anthony Robbins, the nation's leader in the science of peak performance, shows you his most effective strategies and techniques for mastering your emotions, your body, your relationships, your finances, and your life.	", BookIndex = 	4200 });
            Add(new() { Id = new Guid("1a40d746-6b93-4e6c-b59d-100ad3209597"), Name = "Master key system: tečaj samouresničitve   ", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Master Key System temelji na znanstvenih resnicah in omogoča razvoj posameznikovih sposobnosti. S posameznimi koraki, ki se med seboj povezujejo in nadgrajujejo nas uči, kako svoje sposobnosti spremenimo v dejanja, kako povečamo osebno učinkovitost in kako si pridobimo več energije, življenjske moči, postanemo bistroumnejši in umsko prožnejši.", BookIndex =  4300 });
            Add(new() { Id = new Guid("4c72342e-50c0-499c-a3d5-b057d981c280"), Name = "O managementu", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Peter Drucker, eden vodilnih piscev o praksi in teoriji managementa, je skoraj pol stoletja pisal za managerje in vplival na naravo poslovanja podjetij in organizacij.V knjigi je objavljen izbor najboljših Druckerjevih člankov, ki so bili objavljeni v reviji Harvard Business Review med letoma 1950 in 1995.", BookIndex =  4400 });
            Add(new() { Id = new Guid("a15c2636-4997-4580-84eb-5c1c3ab13812"), Name = "The 100 Best Business Books of All Time: What They Say, Why They Matter, and How They Can Help You ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "After years of reading, evaluating, and selling business books, Jack Covert and Todd Sattersten are among the most respected experts on the category. Now they have chosen and reviewed the one hundred best business titles of all time—the ones that deliver the biggest payoff for today’s busy readers.", BookIndex =  4500 });
            Add(new() { Id = new Guid("b8f3641d-a07e-40c2-9e50-af86150a1105"), Name = "The Big Miss: My Years Coaching Tiger Woods", GenreID = new Guid("dad56ba5-640c-4ec1-accb-35463c824b12"), Active = true, Description = "Hank Haney's candid, surprisingly insightful account of his tumultuous six-year journey with Tiger Woods, during which the supremely gifted golfer collected six major championships and rewrote golf history. Hank was one of very few people allowed behind the curtain and observed Tiger in nearly every circumstance. There's never been a book about Tiger that is as intimate and revealing--or as wise about what it takes to coach a star athlete.", BookIndex =  4600 });
            Add(new() { Id = new Guid("ea21bddd-6675-466c-86ee-c02f3619e456"), Name = "Financial Management: Theory and Practice  ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "The only text to strike a balance between solid financial theory and practical applications, Brigham / Ehrhardt�s FINANCIAL MANAGEMENT: THEORY AND PRACTICE, 15e gives you a thorough understanding of the essential concepts you need to develop and implement effective financial strategies.The book begins with a presentation of corporate finance fundamentals before progressing to discussions of specific techniques used to maximize the value of a firm.It also explores the recent financial and economic crises and the role of finance in the business world.With its relevant and engaging presentation, numerous examples, and emphasis on Excel usage, this text serves as a complete reference tool for you in your academic or business career.The 15th edition is also available with MindTap Finance to help you to become First in Finance.", BookIndex =  4700 });
            Add(new() { Id = new Guid("65f8ca71-a5a5-401e-855c-6b1ce1f58aae"), Name = "Psi prodaje", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Ko znaš prodajati, znaš ustvariti dohodek kadarkoli in kjerkoli.Prodaja je srce vsakega posla.Ni treba da ste napadalen pes, da bi uspeli v prodaji.", BookIndex =  4800 });
            Add(new() { Id = new Guid("aa5dafc9-7995-44b0-8f09-281c836a455c"), Name = "Ste za akcijo  ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "   ", BookIndex = 4900 });
            Add(new() { Id = new Guid("2502db5e-3b84-4b1f-be4c-242521e06664"), Name = "Zaključevanje prodajnih pogajanj   ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Kako obvladati strankine izgovore in doseči, da bo kupila pri vas ?", BookIndex = 5000 });
            Add(new() { Id = new Guid("dca46393-c568-4001-8e23-3a2e0492d4e0"), Name = "Revolucija z inovativnostjo do uspeha! 1.del   ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "   ", BookIndex = 5100 });
            Add(new() { Id = new Guid("f63346a8-fae7-413c-bff2-dbf4a0edf209"), Name = "Prodaja. : strategije prihodnosti : Top selling professional: biblija vrhunskega prodajnika", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "Knjiga Prodaja, z ambicioznim podnaslovom Biblija vrhunskega prodajnika, vam zagotavlja konkretne korake za doseganje vrhunskih rezultatov. V knjigi najdete primere uspešnega pogajanja, upravljanja z ugovori, primere postavljanja kraljevskih vprašanj in v prvi vrsti metode, ki vas popeljejo do zaključka prodaje že na začetku prodajnega sestanka. Dodana vrednost knjige je zagotovo praktična naravnanost obeh avtorjev, ki sta v prodajo vsakodnevno vključena tudi sama.	", BookIndex =  5200 });
            Add(new() { Id = new Guid("c5f70a82-af6e-4eb5-a22a-b26a0c268664"), Name = "Priročnik ISO 9001:2015: Razumevanje in izvajanje novih zahtev", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "   ", BookIndex = 5300 });
            Add(new() { Id = new Guid("f1d159ac-e050-47b8-8cf4-dcecd095ef91"), Name = "Ne vseh bonbonov hkrati!   ", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Skrivnost sladkega uspeha v poslu in življenju Uspešni ljudje se zavedajo, da morajo za dosego tistega, česar si res želijo, ponujeno pogosto preložiti. Avtorja nas v očarljivem slogu poučita, kako z načrtovanimi in postopnimi koraki pridemo do točke, ko lahko rečemo: ‚Zmagal sem!‘ 	", BookIndex =  5400 });
            Add(new() { Id = new Guid("0c05a0aa-b969-4bc9-8c35-bddb6618d49d"), Name = "The Secret: Skrivnost", GenreID = new Guid("9456A8FF-2722-4CE6-A67A-91C9CFCD60FC"), Active = true, Description = "Now 'the secret' is being shared with the world.Beautiful in its simplicity, and mind - dazzling in its ability to really work, The Secret reveals the mystery of the hidden potential within us all. By unifying leading - edge scientific thought with ancient wisdom and spirituality, the riveting, practical knowledge will lead readers to a greater understanding of how they can be the masters of their own lives.", BookIndex =  5500 });
            Add(new() { Id = new Guid("41b94a0e-75a7-47ec-8b6a-c39ecb2c99a9"), Name = "The Flow System: The Evolution of Agile and Lean Thinking in an Age of Complexity  ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "he Flow System is a holistic FLOW based approach to delivering Customer 1st Value. It is built on a foundation of the Toyota Production System(TPS / LEAN) and the new Triple Helix of Flow creating the DNA of Organizations.	", BookIndex =  5600 });
            Add(new() { Id = new Guid("0bc39c50-440e-4dd6-a06f-7ee0ddbf36bf"), Name = "Code That Fits in Your Head : Heuristics for Software Engineering  ", GenreID = new Guid("E74EC0D0-4F62-424A-A876-1ED6815E9DE5"), Active = true, Description = "How to Reduce Code Complexity and Develop Software More Sustainably", BookIndex = 5700 });
            Add(new() { Id = new Guid("285f548e-a3ff-4dea-b02b-3d423ba0061f"), Name = "OD IDEJE DO DENARJA: Podjetniški proces    ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "   ", BookIndex = 5800 });
            Add(new() { Id = new Guid("4da9369d-9d97-413d-9d79-ac7c7996325f"), Name = "C# 10 and .NET 6 – Modern Cross-Platform Development", GenreID = new Guid("E74EC0D0-4F62-424A-A876-1ED6815E9DE5"), Active = true, Description = "   ", BookIndex = 	5900 });
            Add(new() { Id = new Guid("c730eedf-d6b7-4b25-b89c-fc5ab9e5b9a1"), Name = "Ekonomija podjetja ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "   ", BookIndex = 6000 });
            Add(new() { Id = new Guid("7dd9600e-f823-4472-90ea-6e801cd722e5"), Name = "Zasebnost in varovanje osebnih podatkov", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "   ", BookIndex = 6100 });
            Add(new() { Id = new Guid("132c3c7c-29d7-4f1f-a439-2e6448fa2d05"), Name = "Zasebnost in varovanje osebnih podatkov, 2.del ", GenreID = new Guid("F3C5B486-D668-4A48-9EC0-66804E40CC0A"), Active = true, Description = "   ", BookIndex = 6200 });
        }
    }
}
